
[global]
python_version = "3.10"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[client]
caching = true
toolbarMode = "minimal"

[logger]
level = "info"
